#cloud-config
package_update: true
packages:
  - wireguard
  - iptables-persistent
  - qrencode
  - unbound
  - unbound-anchor
  - socat

write_files:
  - path: /usr/local/bin/setup-wireguard.sh
    permissions: "0700"
    owner: root:root
    content: |
      #!/bin/bash
      set -e

      # Detect external interface (you can hardcode if needed)
      EXT_IF="ens5"

      # Create key directory
      mkdir -p /etc/wireguard
      cd /etc/wireguard
      umask 077

      # Generate server keys
      wg genkey | tee server_private.key | wg pubkey > server_public.key
      SERVER_PRIVATE_KEY=$(cat server_private.key)

      # Create wg0.conf without any peers
      cat > /etc/wireguard/wg0.conf <<EOF
      [Interface]
      Address = 192.168.2.1/24
      ListenPort = 51820
      PrivateKey = $SERVER_PRIVATE_KEY
      PostUp = iptables -A FORWARD -i wg0 -o $EXT_IF -j ACCEPT; iptables -t nat -A POSTROUTING -o $EXT_IF -j MASQUERADE
      PostDown = iptables -D FORWARD -i wg0 -o $EXT_IF -j ACCEPT; iptables -t nat -D POSTROUTING -o $EXT_IF -j MASQUERADE
      EOF

      # Enable IP forwarding
      echo "net.ipv4.ip_forward=1" > /etc/sysctl.d/99-wireguard.conf
      sysctl -p /etc/sysctl.d/99-wireguard.conf

      # Flush existing rules just in case
      iptables -F
      iptables -t nat -F

      # Set minimal required rules
      iptables -P INPUT ACCEPT
      iptables -P FORWARD ACCEPT
      iptables -P OUTPUT ACCEPT
      iptables -A INPUT -p tcp --dport 22 -j ACCEPT
      iptables -A INPUT -p udp --dport 51820 -j ACCEPT
      iptables -A INPUT -p tcp --dport 8080 -j ACCEPT
      iptables -t nat -A PREROUTING -i wg0 -p udp --dport 53 -j DNAT --to-destination 192.168.2.1
      netfilter-persistent save

      # Configure Unbound root DNS
      curl -o /var/lib/unbound/root.hints https://www.internic.net/domain/named.root
      unbound-anchor -a /var/lib/unbound/root.key || true

      # Fix permissions for unbound user
      chown unbound:unbound /var/lib/unbound/root.key
      chmod 644 /var/lib/unbound/root.hints

      cat > /etc/unbound/unbound.conf.d/wireguard.conf <<EOF_UNBOUND
      server:
          interface: 0.0.0.0
          access-control: 127.0.0.0/8 allow
          access-control: 192.168.2.0/24 allow
          root-hints: "/var/lib/unbound/root.hints"
          do-ip4: yes
          do-udp: yes
          do-tcp: yes
          hide-identity: yes
          hide-version: yes
          harden-glue: yes
          harden-dnssec-stripped: yes
          use-caps-for-id: yes
          qname-minimisation: yes
          prefetch: yes
      EOF_UNBOUND

      # Stop and disable systemd-resolved
      systemctl disable --now systemd-resolved || true
      rm -f /etc/resolv.conf
      echo "nameserver 127.0.0.1" > /etc/resolv.conf

      # Start Unbound
      systemctl enable unbound
      systemctl restart unbound

      # Start WireGuard
      systemctl enable wg-quick@wg0
      systemctl start wg-quick@wg0

      # Start socat TCP listener for GA health check on port 8080
      nohup socat TCP-LISTEN:8080,reuseaddr,fork EXEC:'echo -e "HTTP/1.1 200 OK\r\nContent-Length: 0\r\n\r\n"' > /dev/null 2>&1 &

runcmd:
  - bash /usr/local/bin/setup-wireguard.sh
