#cloud-config
package_update: true
packages:
  - wireguard
  - iptables-persistent
  - qrencode

write_files:
  - path: /usr/local/bin/setup-wireguard.sh
    permissions: "0700"
    owner: root:root
    content: |
      #!/bin/bash
      set -e

      # Detect external interface (you can hardcode if needed)
      EXT_IF="ens3"

      # Create key directory
      mkdir -p /etc/wireguard
      cd /etc/wireguard
      umask 077

      # Generate server keys
      wg genkey | tee server_private.key | wg pubkey > server_public.key
      SERVER_PRIVATE_KEY=$(cat server_private.key)

      # Create wg0.conf without any peers
      cat > /etc/wireguard/wg0.conf <<EOF
      [Interface]
      Address = 192.168.2.1/24
      ListenPort = 51820
      PrivateKey = $SERVER_PRIVATE_KEY
      PostUp = iptables -A FORWARD -i wg0 -o $EXT_IF -j ACCEPT; iptables -t nat -A POSTROUTING -o $EXT_IF -j MASQUERADE
      PostDown = iptables -D FORWARD -i wg0 -o $EXT_IF -j ACCEPT; iptables -t nat -D POSTROUTING -o $EXT_IF -j MASQUERADE
      EOF

      # Enable IP forwarding
      echo "net.ipv4.ip_forward=1" > /etc/sysctl.d/99-wireguard.conf
      sysctl -p /etc/sysctl.d/99-wireguard.conf

      # Flush existing rules just in case
      iptables -F
      iptables -t nat -F

      # Set minimal required rules
      iptables -P INPUT ACCEPT
      iptables -P FORWARD ACCEPT
      iptables -P OUTPUT ACCEPT
      iptables -A INPUT -p tcp --dport 22 -j ACCEPT
      iptables -A INPUT -p udp --dport 51820 -j ACCEPT
      netfilter-persistent save

      # Start WireGuard
      systemctl enable wg-quick@wg0
      systemctl start wg-quick@wg0

runcmd:
  - bash /usr/local/bin/setup-wireguard.sh
